[2022-05-23 17:24:54,520] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: httpChartDag.parseHttp manual__2022-05-23T14:24:52.870655+00:00 [queued]>
[2022-05-23 17:24:54,527] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: httpChartDag.parseHttp manual__2022-05-23T14:24:52.870655+00:00 [queued]>
[2022-05-23 17:24:54,527] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-23 17:24:54,527] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-05-23 17:24:54,527] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-23 17:24:54,536] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): parseHttp> on 2022-05-23 14:24:52.870655+00:00
[2022-05-23 17:24:54,538] {standard_task_runner.py:52} INFO - Started process 39457 to run task
[2022-05-23 17:24:54,542] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'httpChartDag', 'parseHttp', 'manual__2022-05-23T14:24:52.870655+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/httpChartDag.py', '--cfg-path', '/var/folders/0d/sktr6mh10ll3pgqmdz0_b6pw0000gn/T/tmpqtemcl50', '--error-file', '/var/folders/0d/sktr6mh10ll3pgqmdz0_b6pw0000gn/T/tmpx423e48g']
[2022-05-23 17:24:54,544] {standard_task_runner.py:80} INFO - Job 57: Subtask parseHttp
[2022-05-23 17:24:54,580] {task_command.py:369} INFO - Running <TaskInstance: httpChartDag.parseHttp manual__2022-05-23T14:24:52.870655+00:00 [running]> on host 192.168.1.89
[2022-05-23 17:24:54,620] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=httpChartDag
AIRFLOW_CTX_TASK_ID=parseHttp
AIRFLOW_CTX_EXECUTION_DATE=2022-05-23T14:24:52.870655+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-23T14:24:52.870655+00:00
[2022-05-23 17:27:05,061] {process_utils.py:125} INFO - Sending Signals.SIGTERM to group 39457. PIDs of all processes in the group: [39457]
[2022-05-23 17:27:05,062] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 39457
[2022-05-23 17:27:05,063] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-05-23 17:27:05,069] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/mohammadrezakhorasanchian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/Users/mohammadrezakhorasanchian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/mohammadrezakhorasanchian/airflow/dags/httpChartDag.py", line 134, in _parseHttp
    db.collection(u'GetRequests').document(str(hash(str(x)))).set(data)
  File "/Users/mohammadrezakhorasanchian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/google/cloud/firestore_v1/document.py", line 167, in set
    write_results = batch.commit(**kwargs)
  File "/Users/mohammadrezakhorasanchian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/google/cloud/firestore_v1/batch.py", line 59, in commit
    commit_response = self._client._firestore_api.commit(
  File "/Users/mohammadrezakhorasanchian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/google/cloud/firestore_v1/services/firestore/client.py", line 1001, in commit
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/Users/mohammadrezakhorasanchian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 154, in __call__
    return wrapped_func(*args, **kwargs)
  File "/Users/mohammadrezakhorasanchian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
    return retry_target(
  File "/Users/mohammadrezakhorasanchian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/Users/mohammadrezakhorasanchian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/Users/mohammadrezakhorasanchian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/grpc/_channel.py", line 944, in __call__
    state, call, = self._blocking(request, timeout, metadata, credentials,
  File "/Users/mohammadrezakhorasanchian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/grpc/_channel.py", line 933, in _blocking
    event = call.next_event()
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 338, in grpc._cython.cygrpc.SegregatedCall.next_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 169, in grpc._cython.cygrpc._next_call_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 163, in grpc._cython.cygrpc._next_call_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/completion_queue.pyx.pxi", line 76, in grpc._cython.cygrpc._latent_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/completion_queue.pyx.pxi", line 59, in grpc._cython.cygrpc._internal_latent_event
  File "src/python/grpcio/grpc/_cython/_cygrpc/completion_queue.pyx.pxi", line 40, in grpc._cython.cygrpc._next
  File "/Users/mohammadrezakhorasanchian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1543, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2022-05-23 17:27:05,081] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=httpChartDag, task_id=parseHttp, execution_date=20220523T142452, start_date=20220523T142454, end_date=20220523T142705
[2022-05-23 17:27:05,089] {standard_task_runner.py:92} ERROR - Failed to execute job 57 for task parseHttp (Task received SIGTERM signal; 39457)
[2022-05-23 17:27:05,120] {process_utils.py:75} INFO - Process psutil.Process(pid=39457, status='terminated', exitcode=1, started='17:24:54') (39457) terminated with exit code 1
