[2022-05-23 16:12:59,347] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: httpChartDag.parseHttp scheduled__2022-05-22T00:00:00+00:00 [queued]>
[2022-05-23 16:12:59,352] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: httpChartDag.parseHttp scheduled__2022-05-22T00:00:00+00:00 [queued]>
[2022-05-23 16:12:59,352] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-23 16:12:59,352] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-05-23 16:12:59,352] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-23 16:12:59,360] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): parseHttp> on 2022-05-22 00:00:00+00:00
[2022-05-23 16:12:59,363] {standard_task_runner.py:52} INFO - Started process 36297 to run task
[2022-05-23 16:12:59,368] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'httpChartDag', 'parseHttp', 'scheduled__2022-05-22T00:00:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/httpChartDag.py', '--cfg-path', '/var/folders/0d/sktr6mh10ll3pgqmdz0_b6pw0000gn/T/tmp79rcx2qr', '--error-file', '/var/folders/0d/sktr6mh10ll3pgqmdz0_b6pw0000gn/T/tmp5vpwjol6']
[2022-05-23 16:12:59,369] {standard_task_runner.py:80} INFO - Job 51: Subtask parseHttp
[2022-05-23 16:12:59,405] {task_command.py:369} INFO - Running <TaskInstance: httpChartDag.parseHttp scheduled__2022-05-22T00:00:00+00:00 [running]> on host 192.168.1.89
[2022-05-23 16:12:59,446] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=httpChartDag
AIRFLOW_CTX_TASK_ID=parseHttp
AIRFLOW_CTX_EXECUTION_DATE=2022-05-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-22T00:00:00+00:00
[2022-05-23 16:12:59,447] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/mohammadrezakhorasanchian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/Users/mohammadrezakhorasanchian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/mohammadrezakhorasanchian/airflow/dags/httpChartDag.py", line 29, in _parseHttp
    f = open("http.log", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'http.log'
[2022-05-23 16:12:59,451] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=httpChartDag, task_id=parseHttp, execution_date=20220522T000000, start_date=20220523T131259, end_date=20220523T131259
[2022-05-23 16:12:59,458] {standard_task_runner.py:92} ERROR - Failed to execute job 51 for task parseHttp ([Errno 2] No such file or directory: 'http.log'; 36297)
[2022-05-23 16:12:59,469] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-23 16:12:59,485] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
